### ISSUE TITLE
Syntax_error

### ISSUE THREAD

**Issue by nh246** [SyedaJannatul/DIIT_Object-Oriented-Programming#1]
lab class code/Practical_2.cpp 
I think there is a Syntax error in OOP > practical-2 code Because of the class name time, which conflicts with the standard library function time() 
#lab class code/Practical_2.cpp

**Comment by SyedaJannatul** [comment]
It will,if I add here a time header file, i.e. #include<time.h>.But I did
not use the time header file,that's why no error generated here.Try it and
observe the result.

**Comment by nh246** [comment]
ok
